version: '3'

#NETWORK
networks:
   web-net:
    external: true

#SERVICES
services:
  manager-request:
    hostname: manager-request
    container_name: manager-request
    image: huynhcuongem75/manager-request:v.14
    build: 
        context: ./
        dockerfile: ./Manager_Request/Dockerfile
    restart: always
    volumes:
      -  D:\Backup\test:/app/wwwroot/FileUpload/Task

    networks:
      - web-net
    ports:
      - 1010:80
